version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn verify -Pintegration-tests -Dexclude.category=${EXCLUDE_CATEGORY} -Dinclude.category="**/*.java"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/**/*
